config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#root"
  get '/by_date', to: 'static_pages#accounts_by_date', as: 'accounts_by_date'
  patch '/accounts', to: 'accounts#update_multiple', as: 'update_multiple'
  devise_for :users
  resources :accounts
  resources :reports, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def root
    render :root
  end

  def accounts_by_date
    if date_params[:date] != "" && date_params[:location] != ""
      acc_arr = fetch_records(date_params[:location], date_params[:date])
      acc_arr.each do |acc|
        if !Account.find_by(invoice_number: acc["invoice_numb"])
          Account.create(location: acc["cost_ctr"].downcase,
          customer_id: acc["cust_code"],
          customer: acc["cust_name"],
          invoice_number: acc["invoice_numb"],
          route_number: acc["route_code"],
          amount_owed: acc["Total"],
          ship_date: acc["ship_date"],
          amount_received: nil
          )
        end
      end
      redirect_to controller: 'accounts', action: 'index', account_attr: date_params
    else
      flash[:alert] = "Please fill in both fields with valid inputs"
      redirect_to controller: 'static_pages', action: "root"
    end
  end

  private

  def date_params
    params.require(:static_pages).permit(:date, :location)
  end
end

app/views/static_pages/root.html.erb
<form class="date_form" action="<%= accounts_by_date_path %>" method="get">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label for="">Select Shipping Date
      <input type="date" name="static_pages[date]" value="<%= Date.today %>">
    </label>
    <label for="">Enter Cost Center (2 characters)
      <input type="text" name="static_pages[location]" value="">
    </label>
    <input type="submit" name="" value="submit">
</form>