config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#root"
  get '/by_date', to: 'static_pages#accounts_by_date', as: 'accounts_by_date'
  patch '/accounts', to: 'accounts#update_multiple', as: 'update_multiple'
  devise_for :users
  resources :accounts
  resources :reports, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id                        :bigint(8)        not null, primary key
#  ship_date                 :date             not null
#  invoice_number            :integer
#  route_number              :string          not null
#  customer_id               :string           not null
#  customer                  :string           not null
#  amount_owed               :integer
#  extra                     :integer
#  amount_received           :integer
#  amount_credit             :integer
#  received_as_check_or_cash :string
#  logistics_agent_initials  :string
#  reason_code               :string
#  reason_detail            :string
#  credit                    :integer
#  accounting_completed      :boolean
#  accounting_completed_date :datetime
#  location                  :string           not null
#  logistics_completed       :boolean
#  logistics_completed_date  :datetime
#

class Account < ApplicationRecord
  def self.reasons
    [nil,
      "Driver Error",
    "Drop Approved by Credit",
    "Drop Approved by Regional Manager",
    "Returned - Credit in process",
    "Short Paid - Pricing issue - Sales to investigate",
    "Short Paid - Product missing - Credit pending"]
  end
  self.table_name = "dartaccounts"
  before_save :default_completed
  before_update :check_logi_complete
  before_validation :strip_whitespace
  validates :ship_date, :route_number, :customer_id, :customer, presence: true
  validates :invoice_number, uniqueness: true
  validates :logistics_agent_initials, presence: true, :if => :owed_vs_received
  validates :logistics_agent_initials, :length => {:maximum => 2}, :if => :owed_vs_received
  validate :check_logi_complete, on: :update
  validate :save_completed_dates, on: :update
  validates :reason_code, :inclusion => {:in =>  [nil,
    "",
    "Driver Error",
    "Drop Approved by Credit",
    "Drop Approved by Regional Manager",
    "Returned - Credit in process",
    "Short Paid - Pricing issue - Sales to investigate",
    "Short Paid - Product missing - Credit pending"]}

  def default_completed
    self.logistics_completed ||= false
    self.accounting_completed ||= false
  end

  def owed_vs_received
    return false if !self.amount_received
    return false if self.amount_owed == 0
    return false if self.amount_received == nil
    return (self.amount_owed <=> self.amount_received) <= 0
  end

  def check_logi_complete
    return false if self.amount_received == nil
    rec_ammount = self.amount_received
    owed = self.amount_owed
    self.logistics_completed = rec_ammount >= owed ? true : false
  end

  def save_completed_dates
    date = Date.today
    self.logistics_completed_date = self.logistics_completed == true ? date : nil
    self.accounting_completed_date = self.accounting_completed == true ? date : nil
  end

  def strip_whitespace
    self.attributes.each do |pair|
      if pair[-1].is_a? String
        pair[-1].strip!
      end
    end
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    @user_role = current_user.role
    @completed_filter = params[:completed] == "true" ? true : false
    date = params[:account_attr][:date]
    type_completed = current_user.role == "accounting" ? "accounting_completed" : "logistics_completed"
    @accounts = Account.where("((ship_date between ? and ?) and #{type_completed} = ? and location = ?) or #{type_completed} = ?", date, "#{date} 23:59:59", @completed_filter, params[:account_attr][:location].downcase, @completed_filter)
    @accounts = @accounts.sort_by{|account| [ (account.ship_date == params[:account_attr][:date] ? 0 : 1), account.route_number.to_i, account.route_number ] }
    @secondary_attr = [
      "credit",
      "id",
      "logistics_completed",
      "accounting_completed",
      "created_at",
      "updated_at"
    ]
  end

  def update_multiple
    new_attrs_hash = parse_params(account_params)
    new_val_accounts = []
    new_attrs_hash.keys.each do |id|
      account = Account.find(id)
      account.assign_attributes(new_attrs_hash[id])
      new_val_accounts << account
    end
    errors = check_all_for_valid(new_val_accounts) || {}
    if errors.empty?
      new_val_accounts.each do |account|
        account.save
      end
      redirect_to controller: 'accounts', action: 'index', account_attr: { date: params[:date], location: params[:location] }
    else
      flash[:account_errors] = errors
      hash = {"date": params[:date], "location": params[:location]}
      redirect_to controller: 'accounts', action: 'index', :account_attr => { date: params[:date], location: params[:location] }
    end
  end

  def new

  end

  def create

  end

  def update
    # @account = Account.find(params[:id])
    # param_copy = account_params
    # if param_copy[:logistics_agent_initials]
    #   param_copy[:logistics_agent_initials] = param_copy[:logistics_agent_initials].downcase
    # end
    # if current_user.role == "accounting"
    #   param_copy[:accounting_completed] = account_params[:accounting_completed] == "true" ? true : false
    # end
    # if @account.update_attributes(param_copy)
    #   redirect_to controller: 'accounts', action: 'index', account_attr: { date: params[:date], location: params[:location] }
    # else
    #   flash.now[:alert] = @account.errors.full_messages
    #   render :index
    # end
  end

  private

  def account_params
    params.require(:accounts).permit({
      accounts: [
        account: [
          :id,
          :amount_received,
          :amount_credit,
          :received_as_check_or_cash,
          :logistics_agent_initials,
          :reason_code,
          :reason_detail,
          :credit,
          :logistics_completed,
          :accounting_completed
        ]
      ]
    })
    # array of ids:
    # params[:accounts][:accounts].each {|account| account["account"]["id"]}
  end

  def parse_params(params)
    copy = params.clone
    hash = Hash.new()
    params[:accounts].each do |account|
      val = account["account"].clone
      val.delete("id")
      hash[account["account"]["id"].to_i] = val

    end
    return hash
  end

  def check_all_for_valid(arr)
    errors = {}
    arr.each do |account|
      if !account.valid?
        errors[account.id] = account.errors.full_messages
      end
    end
    return errors
  end

  def save_all_updates(arr)
    arr.each do |account|
      account.save
    end
  end

end

app/views/accounts/_row_form.html.erb
  <tr id="<%= account.id %>" class="row<%= idx %> rows">
    <td><%= account.ship_date.strftime("%m/%d/%Y") %></td>
    <td><%= account.invoice_number %></td>
    <td><%= account.route_number %></td>
    <td><%= account.customer_id %></td>
    <td><%= account.customer %></td>
    <td><%= account.amount_owed %></td>
    <td><%= account.extra %></td>

    <%# hidden input for id %>

    <input
    type="hidden"
    name="accounts[accounts][]account[id]"
    value="<%= account.id %>">


    <%# amount_received %>

    <td>
      <input
      class="amount_received"
      type="number"
      step="0.01"
      name="accounts[accounts][]account[amount_received]"
      value="<%= account.amount_received  %>">
    </td>

    <%# amount_credit %>

    <% if current_user.role == "accounting" %>
      <td>
        <input
        class="amount_credit"
        type="number"
        step="0.01"
        name="accounts[accounts][]account[amount_credit]"
        value="<%= account.amount_credit %>">
      </td>
    <% end %>

    <%# received_as_check_or_cash %>

    <td>
      <input
      class="received_as_check_or_cash"
      type="text"
      name="accounts[accounts][]account[received_as_check_or_cash]"
      value="<%= account.received_as_check_or_cash %>">
    </td>

    <%# logistics_agent_initials %>

    <td>
      <input
      class="logistics_agent_initials"
      type="text"
      name="accounts[accounts][]account[logistics_agent_initials]"
      value="<%= account.logistics_agent_initials %>">
    </td>

    <%# reason_code %>

    <td class="reason_select">
      <select
      class="reason_code"
      name="accounts[accounts][]account[reason_code]">
      <% Account.reasons.each do |reason| %>
        <% if account.reason_code == reason %>
          <option selected="selected" value="<%= reason %>"><%= reason %></option>
        <% else %>
          <option value="<%= reason %>"><%= reason %></option>
        <% end %>
      <% end %>
      </select>
    </td>

    <%# reason_detail %>

    <td>
      <textarea
      class="reason_detail"
      name="accounts[accounts][]account[reason_detail]"
      cols="20"
      rows="1"
      ><%= account.reason_detail %></textarea>
    </td>

    <!-- location -->

    <td>
      <%= account.location.upcase %>
    </td>

    <%# accounting_completed %>

      <% if @user_role == "accounting"%>
        <% if account.accounting_completed == false %>
          <td class="checkbox">
            <input class="acc_completed" type="checkbox" name="accounts[accounts][]account[accounting_completed]" value="true">
          </td>

          <td>
            Not Completed
          </td>
        <% else %>
          <td class="checkbox">
            <input class="acc_completed" type="checkbox" name="accounts[accounts][]account[accounting_completed]" checked="checked" value="true" disabled>
          </td>
          <td>
            <%= account.accounting_completed_date %>
          </td>
        <% end %>
      <% end %>


    <% if @user_role == "accounting"%>
        <% if account.logistics_completed == true %>
          <td class="checkbox">
            <input
            readonly = "readonly"
            disabled
            class="log_completed"
            type="checkbox"
            checked
            name="accounts[accounts][]account[<%= @user_role %>_completed]"
            value="true"
            >
          </td>
          <td>
            <%= account.logistics_completed_date %>
          </td>
        <% else %>
          <td class="checkbox">
            <input
            readonly = "readonly"
            disabled
            class="log_completed"
            type="checkbox"
            name="accounts[accounts][]account[<%= @user_role %>_completed]"
            value="true"
            >
          </td>
          <td>
            Not Completed
          </td>
        <% end %>
    <% end %>

  </tr>

app/views/accounts/index.html.erb
<h1>Accounts</h1>
<ul class="nav_links">
  <li>
    <%= link_to "View Report", reports_path( :account_attr => {:date => params[:account_attr][:date], :location => params[:account_attr][:location]} ) %>
  </li>
  <li>
    <%= link_to "View Completed", accounts_path( :account_attr => {:date => params[:account_attr][:date], :location => params[:account_attr][:location]}, :completed => "true" ) %>
  </li>
  <li>
    <%= link_to "View Incomplete", accounts_path( :account_attr => {:date => params[:account_attr][:date], :location => params[:account_attr][:location]}) %>
  </li>
</ul>

<ul id="account_errors">
  <% if flash[:account_errors] %>
    <% flash[:account_errors].keys.each do |id| %>
      <% flash[:account_errors][id].each do |error| %>
        <li class="<%= id %> error_list">
          <%= error %>
        </li>
      <% end %>
    <% end %>
  <% end %>
</ul>

  <% if !@accounts %>
    <span>No Accounts to show for the date given</span>
  <% end %>
  <div class="table_div">
    <form class="account_form" action="<%= update_multiple_path(date: params[:account_attr][:date], location: params[:account_attr][:location]) %>" method="POST">
      <input type="hidden" name="_method" value="<%= :patch %>">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <table>
      <tr>
        <% if !@accounts.empty? %>
          <th>Ship Date</th>
          <th>Invoice Number</th>
          <th>Route Number</th>
          <th>Customer ID</th>
          <th>Customer</th>
          <th>Amount Owed</th>
          <th>Extra</th>
          <th>Amount Received</th>
          <% if @user_role == "accounting" %>
            <th>Amount Credit</th>
          <% end %>
          <th>Received As Check or Cash</th>
          <th>Logistics Agent Initials</th>
          <th>Reason code</th>
          <th>Reason Detail</th>
          <th>Location</th>
          <% if @user_role == "accounting" %>
            <th>Accounting Completed</th>
            <th>Accounting Completed Date</th>
            <th>Logistics Completed</th>
            <th>Logistics Completed Date</th>
          <% end %>
        <% end %>
      </tr>
        <% @accounts.each_with_index do |account, idx| %>
          <%= render "row_form.html.erb", account: account, idx: idx %>
        <% end %>
    </table>
    <input type="submit" value="Submit">
  </form>
  </div>




<script type="text/javascript">

  for (let i = 0; i < 1; i++) {
    let id_arr = [];
    document.querySelectorAll('li.error_list').forEach( (el) => (
    id_arr.push(el.className.split(" ")[0])
    ));
    id_arr.forEach( id => (
    document.getElementById(id).style.backgroundColor = "red"
    ))
  }
  $('textarea.reason_detail').focus(function () {
    $(this).animate({rows: '4'}, 150);
  });
  $('textarea.reason_detail').focusout(function () {
    $(this).animate({rows: '1'}, 150);
  });
</script>